-- 코드를 작성해주세요
SELECT 
    ECOLI_CHILD.ID as ID,
    ECOLI_CHILD.GENOTYPE as GENOTYPE,
    ECOLI_PARENT.GENOTYPE as PARENT_GENOTYPE
FROM 
    ECOLI_DATA as ECOLI_CHILD
JOIN
    ECOLI_DATA as ECOLI_PARENT
ON
    ECOLI_CHILD.PARENT_ID = ECOLI_PARENT.ID
WHERE
    (ECOLI_PARENT.GENOTYPE & ECOLI_CHILD.GENOTYPE) = ECOLI_PARENT.GENOTYPE
ORDER BY 1


