-- 코드를 작성해주세요
# FROM FISH_IFNO 
# SELECT COUNT(FISH_TYPE) as FISH_COUNT
# WHERE LENGTH >= 10
SELECT COUNT(A.FISH_TYPE) AS FISH_COUNT 
FROM FISH_INFO A LEFT OUTER JOIN  FISH_NAME_INFO B
ON A.FISH_TYPE = B.FISH_TYPE
WHERE B.FISH_NAME = "BASS" OR B.FISH_NAME = "SNAPPER";